[package]
name = "av1converter"
version = "1.3.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ratatui = "0.30"
crossterm = "0.29"

# Parallel
rayon = "1.11.0"

# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tracing-appender = "0.2.4"

# Utilities
dirs = "6.0.0"
humansize = "2.1.3"
config = "0.15.19"

# Unix-specific to check disk space
[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["fs"] }
