[package]
name = "av1converter"
version = "1.0.0"
description = "A simple TUI tool to convert videos into AV1"
authors = ["Francesco <mi.francesco@gmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.0"
ffmpeg-next = "8.0.0"
anyhow = "1.0.100"
tracing = "0.1.44"

[dev-dependencies]
pkg-config = "0.3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
